DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS roles;

CREATE TABLE accounts (
username VARCHAR(15) NOT NULL PRIMARY KEY,
id_role INT(15) NOT NULL,
password FLOAT(15) NOT NULL,
fullname VARCHAR(50) NOT NULL);

CREATE TABLE roles (
id_role INT(15) AUTO_INCREMENT NOT NULL PRIMARY KEY,
role VARCHAR(15) NOT NULL);

ALTER TABLE transactions ADD CONSTRAINT transactions_item_id_items_item_id FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE accounts ADD CONSTRAINT accounts_id_role_roles_id_role FOREIGN KEY (id_role) REFERENCES roles(id_role) ON DELETE CASCADE ON UPDATE CASCADE;
